name: Lighthouse
on:
  pull_request:

jobs:
  check-scores:
    name: Check Scores
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://deploy-preview-$PR_NUMBER--arnellebalane-v6.netlify.com/
          temporaryPublicStorage: true
          budgetPath: ./budget.json
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
