name: Lighthouse
on:
  pull_request:

jobs:
  check-scores:
    name: Check Scores
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://$GITHUB_SHA--arnellebalane-v6.netlify.com/
      - uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: '.lighthouseci'
