name: Lint
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{runner.os}}-cache-${{hashFiles('**/package-lock.json')}}

      - run: npm ci
      - run: npm run lint
